apiVersion: skaffold/v1beta6
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/yunheli/jenkinxa:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/yunheli/jenkinxa:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: jenkinxa
        chartPath: charts/jenkinxa
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/yunheli/jenkinxa'
          image.tag: '{{.DIGEST_HEX}}'
